-- 코드를 입력하세요
SELECT TO_CHAR(S.SALES_DATE,'YYYY') AS YEAR, TO_CHAR(S.SALES_DATE,'MM') AS MONTH, I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO I, ONLINE_SALE S
WHERE I.USER_ID = S.USER_ID
AND I.GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE,'YYYY'), TO_CHAR(S.SALES_DATE,'MM'), I.GENDER
ORDER BY YEAR, MONTH, GENDER


