-- 코드를 입력하세요
--SELECT TO_CHAR(START_DATE,'FMMM') AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--WHERE TO_CHAR(START_DATE,'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
--GROUP BY CAR_ID, TO_CHAR(START_DATE,'FMMM')
--HAVING COUNT(*)>=5
--ORDER BY TO_DATE(MONTH,'MM'), CAR_ID DESC

SELECT MONTH, CAR_ID, RECORDS
FROM 
(SELECT DISTINCT TO_CHAR(START_DATE, 'MM') AS MONTH,
                 CAR_ID,
                 COUNT(*) OVER(PARTITION BY TO_CHAR(START_DATE, 'MM'), CAR_ID) AS RECORDS,
                 COUNT(*) OVER(PARTITION BY CAR_ID) AS FILTER
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') BETWEEN '2022-08-01' AND '2022-10-31'
)
WHERE FILTER >= 5 
ORDER BY MONTH ASC, CAR_ID DESC